spring.application.name=SpringAIDemo
<<<<<<< HEAD
#spring.ai.openai.api-key=
#spring.ai.anthropic.api-key=
spring.ai.ollama.chat.options.model=deepseek-r1:14b
=======

spring.ai.anthropic.api-key=
spring.ai.ollama.chat.options.model=deepseek-r1:14b

spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.openai.base-url=https://api.groq.com/openai/v1
# Tells Spring AI NOT to add its own duplicate /v1
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
>>>>>>> c901bf8 (added .env)
